config:
  credentials:
  - id: https://github.com/PalomoIFCA/publicsqaas-testing
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/publicsqaas-testing:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/publicsqaas-testing
      repo: https://github.com/PalomoIFCA/publicsqaas-testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing git:
        commands:
        - /usr/bin/env sh .sqa/script.aquamarine_dedicated_seal.sh
        container: qc.acc_pearl_elated_flamingo
  QC.Doc:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sienna_savvy_tarantula.sh
        container: qc.doc_reef_pensive_emu
      github.com/PalomoIFCA/publicsqaas-testing git:
        commands:
        - /usr/bin/env sh .sqa/script.brown_radiant_elk.sh
        container: qc.doc_jet_delighted_gnu
      github.com/PalomoIFCA/publicsqaas-testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.salmon_independent_alpaca.sh
        container: qc.doc_seafoam_inventive_python
  QC.Lic:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.magenta_amused_crow.sh
        container: qc.lic_cyan_reserved_pelican
  QC.Sec:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing bandit:
        commands:
        - /usr/bin/env sh .sqa/script.avocado_whimsical_tarantula.sh
        container: qc.sec_clove_harmonious_tiger
  QC.Sty:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing flake8:
        commands:
        - /usr/bin/env sh .sqa/script.aquamarine_focused_turtle.sh
        container: qc.sty_ceru_dramatic_vulture
  QC.Uni:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing pytest:
        commands:
        - /usr/bin/env sh .sqa/script.navy_warm_caribou.sh
        container: qc.uni_mulberry_careful_rabbit
  QC.Ver:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cyan_savvy_kraken.sh
        container: qc.ver_chili_adventurous_tarantula
timeout: 5400
