config:
  credentials:
  - id: https://github.com/PalomoIFCA/publicsqaas-testing
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/publicsqaas-testing:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/publicsqaas-testing
      repo: https://github.com/PalomoIFCA/publicsqaas-testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing git:
        commands:
        - /usr/bin/env sh .sqa/script.pink_zany_pegasus.sh
        container: qc.acc_indigo_ambitious_tapir
  QC.Doc:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beige_agile_snail.sh
        container: qc.doc_mahogany_aware_stingray
      github.com/PalomoIFCA/publicsqaas-testing git:
        commands:
        - /usr/bin/env sh .sqa/script.bluebell_responsible_alpaca.sh
        container: qc.doc_khaki_tough_chimpanzee
      github.com/PalomoIFCA/publicsqaas-testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.mango_attentive_weasel.sh
        container: qc.doc_linen_enthusiastic_opossum
  QC.Lic:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jasmine_perky_moose.sh
        container: qc.lic_salmon_resilient_orca
  QC.Sec:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing bandit:
        commands:
        - /usr/bin/env sh .sqa/script.powder_loyal_ocelot.sh
        container: qc.sec_blush_enthusiastic_rhinoceros
  QC.Sty:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wave_tranquil_horse.sh
        container: qc.sty_marina_mature_sphinx
  QC.Uni:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing pytest:
        commands:
        - /usr/bin/env sh .sqa/script.violet_forgiving_ocelot.sh
        container: qc.uni_obsidian_affectionate_koala
  QC.Ver:
    repos:
      github.com/PalomoIFCA/publicsqaas-testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.saffron_humble_echidna.sh
        container: qc.ver_flax_romantic_marmoset
timeout: 5400
